name: Run Python Script

on:
  push:
    branches:
      - main
  workflow_dispatch: # מאפשר הפעלה ידנית

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # החלף לגרסה הרצויה של פייתון

    - name: Install dependencies
      run: |
        pip install -r requirements.txt || echo "No requirements file"

    - name: Run Python script
      run: python py.py
